### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by jasonjenssen** [H2-invent/jitsi-admin#237]
Hey,

is there an option to set a default language?

**Comment by h2Entwicklung** [comment]
Hello @jasonjenssen 
up to now there is no way to set the default language.
But you can do this by  changing the 
`config/packages/jms_i18n_routing.yaml file to `
```
jms_i18n_routing:
  default_locale: en
  locales: [de, en, fr, es, vi, zh]
  strategy: prefix_except_default
```
to switch the default language to english.
